# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "ensure the demo production namespace is removed"
  import_role:
    name: "common/namespace/clean"
  vars:
    namespace: "{{ tanzu_app_pipeline.ci.demo.prod_namespace }}"

- name: "ensure the demo integration testing namespace is removed"
  import_role:
    name: "common/namespace/clean"
  vars:
    namespace: "{{ tanzu_app_pipeline.ci.demo.sit_namespace }}"

- name: "ensure the namespace is removed"
  import_role:
    name: "common/namespace/clean"
  vars:
    namespace: "{{ tanzu_app_pipeline.namespace }}"

- name: "ensure the pod security policies are removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "PodSecurityPolicy"
    name:        "{{ item }}"
    api_version: "policy/v1beta1"
  with_items:
    - "{{ tanzu_app_pipeline.git.resource_name }}-psp"
    - "{{ tanzu_app_pipeline.code_analyzer.resource_name }}-psp"

- name: "ensure the cluster-wide rbac resources are removed"
  k8s:
    state:   "absent"
    context: "{{ tanzu_kubectl_context }}"
    kind:    "{{ item.kind }}"
    name:    "{{ item.name }}"
  with_items:
    - name: "{{ tanzu_app_pipeline.git.resource_name }}-psp"
      kind: "ClusterRole"
    - name: "{{ tanzu_app_pipeline.git.resource_name }}-psp"
      kind: "ClusterRoleBinding"
    - name: "{{ tanzu_app_pipeline.code_analyzer.resource_name }}-psp"
      kind: "ClusterRole"
    - name: "{{ tanzu_app_pipeline.code_analyzer.resource_name }}-psp"
      kind: "ClusterRoleBinding"
