# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "ensure the api services are removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "APIService"
    name:        "{{ item }}"
    api_version: "apiregistration.k8s.io/v1"
  with_items:
    - v1beta1.webhook.cert-manager.io
    - v1alpha2.acme.cert-manager.io

- name: "ensure the custom resource definitions are removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "CustomResourceDefinition"
    name:        "{{ item }}"
    api_version: "apiextensions.k8s.io/v1"
  with_items:
    - certificaterequests.cert-manager.io
    - certificates.cert-manager.io
    - challenges.acme.cert-manager.io
    - clusterissuers.cert-manager.io
    - issuers.cert-manager.io
    - orders.acme.cert-manager.io

- name: "ensure the validating webhook configuration is removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "ValidatingWebhookConfiguration"
    name:        "cert-manager-webhook"
    api_version: "admissionregistration.k8s.io/v1"

- name: "ensure the namespace is removed"
  import_role:
    name: "common/namespace/clean"
  vars:
    namespace: "{{ tanzu_security.namespace }}"

- name: "ensure the pod security policy is removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "PodSecurityPolicy"
    name:        "{{ tanzu_security.cert_delivery_job.resource_name }}"
    api_version: "policy/v1beta1"

- name: "ensure the cluster-wide rbac resources are removed"
  k8s:
    state:   "absent"
    context: "{{ tanzu_kubectl_context }}"
    kind:    "{{ item.kind }}"
    name:    "{{ item.name }}"
  with_items:
    - name: "cert-manager-controller-issuers"
      kind: "ClusterRoleBinding"
    - name: "cert-manager-controller-clusterissuers"
      kind: "ClusterRoleBinding"
    - name: "cert-manager-controller-certificates"
      kind: "ClusterRoleBinding"
    - name: "cert-manager-controller-orders"
      kind: "ClusterRoleBinding"
    - name: "cert-manager-controller-challenges"
      kind: "ClusterRoleBinding"
    - name: "cert-manager-controller-ingress-shim"
      kind: "ClusterRoleBinding"
    - name: "cert-manager-cainjector"
      kind: "ClusterRoleBinding"
    - name: "cert-manager-webhook:auth-delegator"
      kind: "ClusterRoleBinding"
    - name: "tanzu-ca-jobs-psp"
      kind: "ClusterRoleBinding"
    - name: "tanzu-ca-jobs"
      kind: "ClusterRoleBinding"
    - name: "cert-manager-cainjector"
      kind: "ClusterRole"
    - name: "cert-manager-webhook:webhook-requester"
      kind: "ClusterRole"
    - name: "cert-manager-controller-issuers"
      kind: "ClusterRole"
    - name: "cert-manager-controller-clusterissuers"
      kind: "ClusterRole"
    - name: "cert-manager-controller-certificates"
      kind: "ClusterRole"
    - name: "cert-manager-controller-orders"
      kind: "ClusterRole"
    - name: "cert-manager-controller-challenges"
      kind: "ClusterRole"
    - name: "cert-manager-controller-ingress-shim"
      kind: "ClusterRole"
    - name: "cert-manager-view"
      kind: "ClusterRole"
    - name: "cert-manager-edit"
      kind: "ClusterRole"
    - name: "tanzu-ca-jobs-psp"
      kind: "ClusterRole"
    - name: "tanzu-ca-jobs"
      kind: "ClusterRole"
