# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
#
# NAMESPACE
#
- name: "ensure manifest staging directory exists"
  import_role:
    name: "common/staging-directory"
  vars:
    staging_dir: "{{ tanzu_app_pipeline.staging_dir }}"

- name: "create namespace"
  import_role:
    name: "common/namespace"
  vars:
    namespace:               "{{ tanzu_app_pipeline.namespace }}"
    namespace_template_file: "tanzu-namespace.yaml.j2"
    namespace_file:          "{{ tanzu_app_pipeline.staging_dir }}/tanzu-namespace.yaml"

#
# DEPLOY TOOLCHAINS
#
- name: "get the ingress ip"
  import_role:
    name: "common/ingress-ip"

- name: "deploy toolchains"
  include_tasks: "{{ item }}.yaml"
  with_items:
    - gitea
    - sonatype-nexus
    - sonarqube
    - jenkins
