# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
#
# JOBS
#
- name: "wait for job {{ _wait_for.result.metadata.name }} to complete"
  include_tasks: "wait-for-job.yaml"
  vars:
  when: _wait_for.result.kind == "Job"
