# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "copy encryption config ytt to staging dir"
  template:
    src: "../templates/remove-encryption-config-kacp.yaml.j2"
    dest: "{{ tanzu_secrets.staging_dir }}/remove-encryption-config-kacp.yaml"
    mode: "0440"
  delegate_to: "localhost"

- name: "collect KubeadmControlPlane object for workload cluster from management cluster"
  k8s_info:
    kind:         "KubeadmControlPlane"
    api_version:  "controlplane.cluster.x-k8s.io/v1alpha3"
    namespace:    "{{ tanzu_secrets.workload_cluster_namespace }}"
    name:         "{{ tanzu_cluster_name }}-control-plane"
    context:      "{{ tanzu_management_cluster_kubectl_context }}"
  register: kacp_orig
  delegate_to: "localhost"

- name: "save KubeadmControlPlane manifest for ytt later"
  copy:
    content: "{{ kacp_orig.resources[0] }}"
    dest: "{{ tanzu_secrets.staging_dir }}/kacp-orig.yaml"
  delegate_to: "localhost"

- name: "generate new KubeadmControlPlane manifest"
  shell:       "/usr/local/bin/ytt -f {{ tanzu_secrets.staging_dir }}/kacp-orig.yaml -f {{ tanzu_secrets.staging_dir }}/remove-encryption-config-kacp.yaml"
  delegate_to: "localhost"
  register:    generated_kacp_manifest

- name: "save generated KubeadmControlPlane manifest"
  copy:
    content: "{{ generated_kacp_manifest.stdout }}"
    dest: "{{ tanzu_secrets.staging_dir }}/kacp-gen.yaml"
  delegate_to: "localhost"

- name: "apply new KubeadmControlPlane manifest"
  k8s:
    state: present
    context: "{{ tanzu_management_cluster_kubectl_context }}"
    namespace: "{{ tanzu_secrets.workload_cluster_namespace }}"
    src: "{{ tanzu_secrets.staging_dir }}/kacp-gen.yaml"

- name: "pause for 3 minutes for control plane node(s) to be recreated"
  pause:
    minutes: 3

- name: "validate that control plane has been updated"
  k8s_info:
    kind:         "KubeadmControlPlane"
    api_version:  "controlplane.cluster.x-k8s.io/v1alpha3"
    namespace:    "{{ tanzu_secrets.workload_cluster_namespace }}"
    name:         "{{ tanzu_cluster_name }}-control-plane"
    context:      "{{ tanzu_management_cluster_kubectl_context }}"
  delegate_to: "localhost"
  register:    kacp
  until:       (kacp.resources[0].status.ready == True) and (kacp.resources[0].spec.replicas == kacp.resources[0].status.replicas) and (kacp.resources[0].status.updatedReplicas == kacp.resources[0].status.readyReplicas)
  retries:     240
  delay:       5
  failed_when: false
