# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "ensure the namespace is removed"
  import_role:
    name: "common/namespace/clean"
  vars:
    namespace: "{{ tanzu_container_registry.namespace }}"
