# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "ensure the namespaces are removed"
  include_role:
    name: "common/namespace/clean"
  vars:
    namespace: "{{ avi.namespace }}"

- name: "ensure the cluster-wide rbac resources are removed"
  k8s:
    state:   "absent"
    context: "{{ tanzu_kubectl_context }}"
    kind:    "{{ item.kind }}"
    name:    "{{ item.name }}"
  with_items:
    - name: "ako-cr"
      kind: "ClusterRole"
    - name: "ako-crb"
      kind: "ClusterRoleBinding"

- name: "ensure the custom resource definitions are removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "CustomResourceDefinition"
    name:        "{{ item }}"
    api_version: "apiextensions.k8s.io/v1"
  with_items:
    - "hostrules.ako.vmware.com"
    - "httprules.ako.vmware.com"
