# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
#
# STORAGE CLASS
#
- name: "ensure aws storage classes exist"
  import_role:
    name: "common/manifest-file"
  vars:
    manifest_description: "aws storage classes"
    manifest_template:    "storage-class-aws.yaml.j2"
    manifest_file:        "storage-class-aws.yaml"
    manifest_staging_dir: "{{ tanzu_storage.staging_dir }}"
