# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
sonobuoy-config:
  driver: Job
  plugin-name: rpk-ingress
  result-format: manual
spec:
  image: cloudnativereadiness/rpk-ingress-validate:0.1
  name: plugin
  resources: {}
  # mountPath must match resultsDir build arg for docker image
  volumeMounts:
    - mountPath: /tmp/results
      name: results

