# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "write {{ manifest_description | lower }} manifest file"
  template:
    src:  "{{ manifest_template }}"
    dest: "{{ manifest_staging_dir }}/{{ manifest_template.split('.j2') | first | basename }}"
    mode: "0440"
    # allow for different templating strings
    variable_start_string: "{{ manifest_variable_start_string | default(omit) }}"
    variable_end_string:   "{{ manifest_variable_end_string | default(omit) }}"
  changed_when: false

- name: "ensure {{ manifest_description | lower }} is present"
  k8s:
    state:   "present"
    context: "{{ tanzu_kubectl_context }}"
    src:     "{{ manifest_staging_dir }}/{{ manifest_template.split('.j2') | first | basename }}"
  register: _resource_status
  until:    not _resource_status.failed
  retries:  30
  delay:    1
