# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "clean manifests with kapp"
  kapp:
    state:        "absent"
    context:      "{{ tanzu_kubectl_context }}"
    namespace:    "{{ rpk_extension_namespace }}"
    name:         "{{ tanzu_role_name.component }}"
    wait_timeout: "{{ wait_timeout | default('300s') }}"
