# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
#
# NAMESPACES
#
- name: "ensure manifest staging directory exists"
  import_role:
    name: "common/staging-directory"
  vars:
    staging_dir: "{{ tanzu_networking.staging_dir }}"

- name: "create namespace"
  import_role:
    name: "common/namespace"
  vars:
    namespace:               "{{ tanzu_networking.namespace }}"
    namespace_template_file: "tanzu-namespace.yaml.j2"
    namespace_file:          "{{ tanzu_networking.staging_dir }}/tanzu-namespace.yaml"

- name: "ensure kube-system namespace has proper labels"
  k8s:
    state:   "present"
    context: "{{ tanzu_kubectl_context }}"
    definition:
      apiVersion: "v1"
      kind:       "Namespace"
      metadata:
        name: "kube-system"
        labels:
          name: "kube-system"

- name: "ensure tmc namespace has proper labels"
  import_role:
    name: "common/tmc-namespace-labels"

- name: "determine the cluster cni"
  import_role:
    name: "common/cluster-cni"

- name: "determine if cluster is a tkg cluster and its version"
  import_role:
    name: "common/tkg-version"

- name: "get the global network policy custom resource definition"
  k8s_info:
    kind:        "CustomResourceDefinition"
    context:     "{{ tanzu_kubectl_context }}"
    api_version: "apiextensions.k8s.io/v1"
    name:        "globalnetworkpolicies.crd.projectcalico.org"
  register: _global_network_policy_crd

- name: "run calico tasks"
  import_tasks: "calico.yaml"
  when: _cluster_cni == 'calico'

- name: "run antrea tasks"
  import_tasks: "antrea.yaml"
  when: _cluster_cni == 'antrea'
