# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "ensure the custom resource definitions are removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "CustomResourceDefinition"
    name:        "{{ item }}"
    api_version: "apiextensions.k8s.io/v1"
  with_items:
    - verticalpodautoscalercheckpoints.autoscaling.k8s.io
    - verticalpodautoscalers.autoscaling.k8s.io

- name: "ensure the mutating webhook configuration is removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "MutatingWebhookConfiguration"
    name:        "vpa-webhook-config"
    api_version: "admissionregistration.k8s.io/v1"

- name: "ensure the namespace is removed"
  import_role:
    name: "common/namespace/clean"
  vars:
    namespace: "{{ tanzu_autoscaling.namespace }}"

- name: "ensure the cluster-wide rbac resources are removed"
  k8s:
    state:   "absent"
    context: "{{ tanzu_kubectl_context }}"
    kind:    "{{ item.kind }}"
    name:    "{{ item.name }}"
  with_items:
    - name: "system:vpa-metrics-reader"
      kind: "ClusterRole"
    - name: "system:vpa-metrics-reader"
      kind: "ClusterRoleBinding"
    - name: "system:vpa-actor"
      kind: "ClusterRole"
    - name: "system:vpa-actor"
      kind: "ClusterRoleBinding"
    - name: "system:vpa-checkpoint-actor"
      kind: "ClusterRole"
    - name: "system:vpa-checkpoint-actor"
      kind: "ClusterRoleBinding"
    - name: "system:vpa-evictioner"
      kind: "ClusterRole"
    - name: "system:vpa-evictioner"
      kind: "ClusterRoleBinding"
    - name: "system:vpa-target-reader"
      kind: "ClusterRole"
    - name: "system:vpa-target-reader"
      kind: "ClusterRoleBinding"
    - name: "system:vpa-admission-controller"
      kind: "ClusterRole"
    - name: "system:vpa-admission-controller"
      kind: "ClusterRoleBinding"
    - name: "system:vpa-status-reader"
      kind: "ClusterRole"
    - name: "system:vpa-status-reader"
      kind: "ClusterRoleBinding"

