# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "ensure the custom resource definitions are removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "CustomResourceDefinition"
    name:        "{{ item }}"
    api_version: "apiextensions.k8s.io/v1"
  with_items:
    - configs.config.gatekeeper.sh
    - constraintpodstatuses.status.gatekeeper.sh
    - constrainttemplatepodstatuses.status.gatekeeper.sh
    - constrainttemplates.templates.gatekeeper.sh

- name: "ensure the validating webhook configuration is removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "ValidatingWebhookConfiguration"
    name:        "gatekeeper-validating-webhook-configuration"
    api_version: "admissionregistration.k8s.io/v1"

- name: "ensure the mutating webhook configuration is removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "MutatingWebhookConfiguration"
    name:        "mutating-webhook-configuration"
    api_version: "admissionregistration.k8s.io/v1"
    namespace:   "{{ tanzu_admission_control.namespace }}"

- name: "ensure the namespace is removed"
  import_role:
    name: "common/namespace/clean"
  vars:
    namespace: "{{ tanzu_admission_control.namespace }}"

- name: "ensure the cluster-wide rbac resources are removed"
  k8s:
    state:   "absent"
    context: "{{ tanzu_kubectl_context }}"
    kind:    "{{ item.kind }}"
    name:    "{{ item.name }}"
  with_items:
    - name: "gatekeeper-manager-role"
      kind: "ClusterRole"
    - name: "gatekeeper-manager-rolebinding"
      kind: "ClusterRoleBinding"
    - name: "gatekeeper-operator-manager-role"
      kind: "ClusterRole"
    - name: "gatekeeper-operator-manager-rolebinding"
      kind: "ClusterRoleBinding"
