# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "ensure kapp component {{ component }} does not exist"
  kapp:
    state:        "absent"
    context:      "{{ tanzu_kubectl_context }}"
    namespace:    "{{ rpk_extension_namespace }}"
    name:         "{{ component }}"
    wait_timeout: "{{ wait_timeout | default('300s') }}"
