# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "ensure the custom resource definitions are removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "CustomResourceDefinition"
    name:        "{{ item }}"
    api_version: "apiextensions.k8s.io/v1"
  with_items:
    - alertmanagers.monitoring.coreos.com
    - podmonitors.monitoring.coreos.com
    - prometheuses.monitoring.coreos.com
    - prometheusrules.monitoring.coreos.com
    - servicemonitors.monitoring.coreos.com
    - thanosrulers.monitoring.coreos.com

- name: "ensure the api services are removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "APIService"
    name:        "v1beta1.metrics.k8s.io"
    api_version: "apiregistration.k8s.io/v1"

- name: "ensure the namespace is removed"
  import_role:
    name: "common/namespace/clean"
  vars:
    namespace: "{{ tanzu_monitoring.namespace }}"

- name: "ensure the cluster-wide rbac resources are removed"
  k8s:
    state:   "absent"
    context: "{{ tanzu_kubectl_context }}"
    kind:    "{{ item.kind }}"
    name:    "{{ item.name }}"
  with_items:
    - name: "grafana-clusterrole"
      kind: "ClusterRole"
    - name: "grafana-clusterrolebinding"
      kind: "ClusterRoleBinding"
    - name: "grafana-role"
      kind: "ClusterRole"
    - name: "grafana-rolebinding"
      kind: "ClusterRoleBinding"
    - name: "prometheus-adapter"
      kind: "ClusterRole"
    - name: "prometheus-adapter"
      kind: "ClusterRoleBinding"
    - name: "prometheus-k8s"
      kind: "ClusterRole"
    - name: "prometheus-k8s"
      kind: "ClusterRoleBinding"
    - name: "prometheus-operator"
      kind: "ClusterRole"
    - name: "prometheus-operator"
      kind: "ClusterRoleBinding"
