# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "ensure the validating webhook configuration is removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "ValidatingWebhookConfiguration"
    name:        "istiod-{{ tanzu_mesh.namespace }}"
    api_version: "admissionregistration.k8s.io/v1"

- name: "ensure the mutating webhook configuration is removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "MutatingWebhookConfiguration"
    name:        "istio-sidecar-injector-{{ tanzu_mesh.image_tag | replace('.', '-') }}-{{ tanzu_mesh.namespace }}"
    api_version: "admissionregistration.k8s.io/v1"
    namespace:   "{{ tanzu_mesh.namespace }}"

- name: "ensure the istio operator deployment is removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "Deployment"
    name:        "istio-operator"
    api_version: "apps/v1"
    namespace:   "{{ tanzu_mesh.namespace }}"
    wait:        true

- name: "ensure the istio operator is removed (pre-finalizer removal)"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "IstioOperator"
    name:        "istiocontrolplane"
    api_version: "install.istio.io/v1alpha1"
    namespace:   "{{ tanzu_mesh.namespace }}"

- name: "ensure the istio operator custom resource definition has its finalizer removed"
  k8s:
    state:       "present"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "IstioOperator"
    name:        "istiocontrolplane"
    api_version: "install.istio.io/v1alpha1"
    namespace:   "{{ tanzu_mesh.namespace }}"
    definition:
      metadata:
        finalizers: []
  ignore_errors: true

- name: "ensure the istio operator is removed (post-finalizer removal)"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "IstioOperator"
    name:        "istiocontrolplane"
    api_version: "install.istio.io/v1alpha1"
    namespace:   "{{ tanzu_mesh.namespace }}"
    wait:        true

- name: "ensure the namespace is removed"
  import_role:
    name: "common/namespace/clean"
  vars:
    namespace: "{{ tanzu_mesh.namespace }}"

- name: "ensure the cluster-wide rbac resources are removed"
  k8s:
    state:   "absent"
    context: "{{ tanzu_kubectl_context }}"
    kind:    "{{ item.kind }}"
    name:    "{{ item.name }}"
  with_items:
    - name: "{{ tanzu_mesh.operator.clusterrole }}"
      kind: "ClusterRole"
    - name: "{{ tanzu_mesh.operator.clusterrolebinding }}"
      kind: "ClusterRoleBinding"

- name: "ensure the custom resource definitions are removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "CustomResourceDefinition"
    name:        "{{ item }}"
    api_version: "apiextensions.k8s.io/v1"
  with_items:
    - adapters.config.istio.io
    - attributemanifests.config.istio.io
    - authorizationpolicies.security.istio.io
    - destinationrules.networking.istio.io
    - envoyfilters.networking.istio.io
    - gateways.networking.istio.io
    - handlers.config.istio.io
    - httpapispecbindings.config.istio.io
    - httpapispecs.config.istio.io
    - instances.config.istio.io
    - peerauthentications.security.istio.io
    - quotaspecbindings.config.istio.io
    - quotaspecs.config.istio.io
    - requestauthentications.security.istio.io
    - rules.config.istio.io
    - serviceentries.networking.istio.io
    - sidecars.networking.istio.io
    - templates.config.istio.io
    - virtualservices.networking.istio.io
    - workloadentries.networking.istio.io

- name: "ensure the api services are removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "APIService"
    name:        "{{ item }}"
    api_version: "apiregistration.k8s.io/v1"
  with_items:
    - v1alpha1.install.istio.io
    - v1alpha2.config.istio.io
    - v1alpha3.networking.istio.io
    - v1beta1.networking.istio.io
    - v1beta1.security.istio.io
