# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "ensure the namespaces are removed"
  include_role:
    name: "common/namespace/clean"
  vars:
    namespace: "{{ item }}"
  with_items:
    - "{{ tanzu_workload_tenancy.demo_namespace }}"
    - "{{ tanzu_workload_tenancy.namespace }}"

- name: "ensure the cluster-wide rbac resources are removed"
  k8s:
    state:   "absent"
    context: "{{ tanzu_kubectl_context }}"
    kind:    "{{ item.kind }}"
    name:    "{{ item.name }}"
  with_items:
    - name: "{{ tanzu_workload_tenancy.namespace_operator.clusterrole }}"
      kind: "ClusterRole"
    - name: "{{ tanzu_workload_tenancy.namespace_operator.clusterrolebinding }}"
      kind: "ClusterRoleBinding"

- name: "ensure the default resource constraints are removed"
  k8s:
    state:     "absent"
    context:   "{{ tanzu_kubectl_context }}"
    kind:      "{{ item.kind }}"
    name:      "{{ item.name }}"
    namespace: "default"
  with_items:
    - name: "tanzu-default-limit-range"
      kind: "LimitRange"
    - name: "tanzu-default-resource-quota"
      kind: "ResourceQuota"

- name: "ensure the custom resource definitions are removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "CustomResourceDefinition"
    name:        "tanzunamespaces.tenancy.platform.cnr.vmware.com"
    api_version: "apiextensions.k8s.io/v1"
