# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "get the global network policy custom resource definition"
  k8s_info:
    kind:        "CustomResourceDefinition"
    context:     "{{ tanzu_kubectl_context }}"
    api_version: "apiextensions.k8s.io/v1"
    name:        "globalnetworkpolicies.crd.projectcalico.org"
  register: _global_network_policy_crd

- name: "get the cluster network policy custom resource definition"
  k8s_info:
    kind:        "CustomResourceDefinition"
    context:     "{{ tanzu_kubectl_context }}"
    api_version: "apiextensions.k8s.io/v1"
    name:        "clusternetworkpolicies.security.antrea.tanzu.vmware.com"
  register: _cluster_network_policy_crd

- name: "determine which cni is in use by checking crds"
  set_fact:
    _cluster_cni: "calico"
  when: (_global_network_policy_crd.resources | length) > 0

- name: "determine which cni is in use by checking crds"
  set_fact:
    _cluster_cni: "antrea"
  when: (_cluster_network_policy_crd.resources | length) > 0
