# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "ensure the calico global network policy is removed"
  k8s:
    state:       "absent"
    context:     "{{ tanzu_kubectl_context }}"
    kind:        "GlobalNetworkPolicy"
    name:        "tanzu-global-deny-all"
    api_version: "crd.projectcalico.org/v1"
