# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "ensure the namespace is removed"
  import_role:
    name: "common/namespace/clean"
  vars:
    namespace: "{{ tanzu_spring_cloud_data_flow.namespace }}"

- name: "ensure the cluster-wide resources are removed"
  k8s:
    state:   "absent"
    context: "{{ tanzu_kubectl_context }}"
    kind:    "{{ item.kind }}"
    name:    "{{ item.name }}"
  with_items:
    - name: "rabbitmq-endpoint-reader-role-binding"
      kind: "RoleBinding"
    - name: "rabbitmq-endpoint-reader"
      kind: "Role"
    - name: "rabbitmq-service-account"
      kind: "ServiceAccount"
    - name: "skipper-rb"
      kind: "RoleBinding"
    - name: "skipper-role"
      kind: "Role"
    - name: "scdf-skipper"
      kind: "ServiceAccount"
    - name: "scdf-data-flow"
      kind: "ServiceAccount"
    - name: "scdf-rb"
      kind: "RoleBinding"
    - name: "scdf-role"
      kind: "Role"
