# Copyright 2006-2021 VMware, Inc.
# SPDX-License-Identifier: MIT
---
- name: "ensure monogodb rbac exists"
  import_role:
    name: "common/manifest-file"
  vars:
    manifest_description: "monogodb rbac"
    manifest_template:    "db/mongodb-rbac.yaml.j2"
    manifest_staging_dir: "{{ tanzu_app_stack.staging_dir }}"

- name: "ensure monogodb config map exists"
  import_role:
    name: "common/manifest-file"
  vars:
    manifest_description: "monogodb config map"
    manifest_template:    "db/mongodb-configmap.yaml.j2"
    manifest_staging_dir: "{{ tanzu_app_stack.staging_dir }}"

- name: "ensure monogodb secret exists"
  import_role:
    name: "common/manifest-file"
  vars:
    manifest_description: "monogodb secret"
    manifest_template:    "db/mongodb-secret.yaml.j2"
    manifest_staging_dir: "{{ tanzu_app_stack.staging_dir }}"

- name: "ensure monogodb config deployment exists"
  import_role:
    name: "common/manifest-file-with-wait"
  vars:
    manifest_description: "monogodb deployment"
    manifest_template:    "db/mongodb-deployment.yaml.j2"
    manifest_staging_dir: "{{ tanzu_app_stack.staging_dir }}"
